coverage:
  status:
    project:
      default: false
      nimbus:
        target: 80%
        paths:
          - "platforms/apple/Sources/Nimbus" #don't include tests
          - "platforms/android/nimbus/src/main" #don't include tests
